# Generated by Django 4.2.6 on 2023-10-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_employer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(upload_to='empleado'),
        ),
    ]
