# Generated by Django 4.2.6 on 2023-10-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_employer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
